name: Labeler

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Check Labels
        id: labeler
        uses: jimschubert/labeler-action@v1
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Add labels based on user
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const author = context.payload.pull_request 
              ? context.payload.pull_request.user.login 
              : context.payload.issue.user.login;

            const frontendUsers = ["hummingbbird", "HeeNamgoong", "seo0o519"];
            const backendUsers = ["hyni03", "mjk25"];
            const aiUsers = ["justpers"];

            let labelsToAdd = [];

            if (frontendUsers.includes(author)) {
              labelsToAdd.push(":nail_care: FRONTEND");
            } 
            if (backendUsers.includes(author)) {
              labelsToAdd.push(":rocket: BACKEND");
            } 
            if (aiUsers.includes(author)) {
              labelsToAdd.push(":page_facing_up: AI");
            }

            if (labelsToAdd.length > 0) {
              github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request 
                  ? context.payload.pull_request.number 
                  : context.payload.issue.number,
                labels: labelsToAdd
              });
            }